DROP TABLE IF EXISTS visit_note CASCADE;
DROP TYPE IF EXISTS visit_status CASCADE;
DROP TABLE IF EXISTS visit CASCADE;
DROP TABLE IF EXISTS medical_history CASCADE;
DROP TABLE IF EXISTS doctor CASCADE;
DROP TYPE IF EXISTS patient_gender CASCADE;
DROP TABLE IF EXISTS patient CASCADE;
