DROP TABLE IF EXISTS visit_note CASCADE;
DROP TYPE IF EXISTS status CASCADE;
DROP TABLE IF EXISTS visit CASCADE;
DROP TABLE IF EXISTS doctor CASCADE;
DROP TABLE IF EXISTS medical_history CASCADE;
DROP TYPE IF EXISTS gender CASCADE;
DROP TABLE IF EXISTS patient CASCADE;
DROP TABLE IF EXISTS flyway_schema_history CASCADE;
